<?php

namespace bim\testBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class AdvertRepository extends EntityRepository
{
    public function AdvertPurge($date)
    {
        $qb=$this->createQueryBuilder('a')
            ->where('a.UpdateAd <= :date')
            ->orWhere('a.UpdateAd iS Null AND a.date <= :date')
            ->andWhere('a.applications IS EMPTY')
            ->setParameter('date',$date);
        return $qb->getQuery()->getResult();

    }
    public function getAdverts()
    {
        $query = $this->createQueryBuilder('a')
            // Jointure sur l'attribut image
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            // Jointure sur l'attribut categories
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            //Jointure sur l'atribut skills
            ->leftJoin('a.skills','s')
            ->addSelect('s')
            ->orderBy('a.date', 'DESC')
            ->getQuery()
        ;

        return $query->getResult();
    }

    public function getAdvertWithApplicationBySlug($slug)
    {
        $qb=$this->createQueryBuilder('a')
            ->innerJoin('a.applications','app')
            ->addSelect('app');

        $qb->where('a.slug = :slug')->setParameter('slug',$slug);
        return $qb->getQuery()->getOneOrNullResult();

    }
}